builds:
  - binary: git-download
    goos:
      - windows
      - darwin
      - linux
    goarch:
      - amd64
      - arm64
    env:
      - CGO_ENABLED=0
    ldflags:
      - -s -w -X main.version={{.Version}}

archives:
  - format: tar.gz
    format_overrides:
      - goos: windows
        format: zip
    replacements:
      darwin: macOS
    files:
      - README.md
      - LICENSE

checksum:
  name_template: 'checksums.txt'

changelog:
  sort: asc
  filters:
    exclude:
      - '^docs:'
      - '^test:'
      - Merge pull request
      - Merge branch

brews:
  - name: git-download
    tap:
      owner: pimentel
      name: homebrew-tools
    folder: Formula
    homepage: https://github.com/pimentel/git-download
    description: Download and sync Git repositories using ZIP files
    license: MIT
    test: |
      system "#{bin}/git-download --version"
    install: |
      bin.install "git-download"

scoop:
  bucket:
    owner: pimentel
    name: scoop-bucket
  homepage: https://github.com/pimentel/git-download
  description: Download and sync Git repositories using ZIP files
  license: MIT

dockers:
  - image_templates:
      - "ghcr.io/pimentel/git-download:{{ .Version }}"
      - "ghcr.io/pimentel/git-download:latest"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=git-download"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/amd64"
  - image_templates:
      - "ghcr.io/pimentel/git-download:{{ .Version }}-arm64"
      - "ghcr.io/pimentel/git-download:latest-arm64"
    dockerfile: Dockerfile
    build_flag_templates:
      - "--pull"
      - "--label=org.opencontainers.image.created={{.Date}}"
      - "--label=org.opencontainers.image.title=git-download"
      - "--label=org.opencontainers.image.revision={{.FullCommit}}"
      - "--label=org.opencontainers.image.version={{.Version}}"
      - "--platform=linux/arm64"
    goarch: arm64